### ISSUE TITLE
It Doesnt Support AndroidX

### ISSUE THREAD

**Issue by EricRootLee** [keronei/mpesa_flutter_plugin#2]
The Plugin is only available for android.support can you create another version for AndroidX.
Thank You.

**Comment by keronei** [comment]
Hello @EricRootLee ,
Please checkout `v0.0.4`. Have fixed a few things as indicated in the changelog. Also test the new version for `androidx` support, feel free to close this issue if your concern has been addressed by the update.
regards.

**Comment by keronei** [comment]
Closing since there has not been any response after fix for 1 month.
