### ISSUE TITLE
Bad Request - Invalid BusinessShortCode

### ISSUE THREAD

**Issue by Brightmuk** [keronei/mpesa_flutter_plugin#4]
For some reason my business short code does not pass. I have tried using the test short code 174379 it works fine but when i replace it with mine it doesn't. I have done a cross check manually and the paybill works fine with lipa na mpesa.

**Comment by keronei** [comment]
Is it in the same format ? Check that you are not adding spaces before or after the code. This seems to be a response from Mpesa processor.

**Comment by Brightmuk** [comment]
`businessShortCode: "151030",`

thats how i put it exaclty

**Comment by keronei** [comment]
You also need to change ‘PartyB’ to reflect the same paybill.

Please confirm if you have done that as well.


There are two entries that are duplicated. 

PartyA -> phoneNumber
PartyB -> businessShortCode

**Comment by keronei** [comment]
Have tested, yes, it doesn’t go through the plugin but is fine on the actual STK.

Will have to troubleshoot further.

**Comment by Brightmuk** [comment]
`     await MpesaFlutterPlugin.initializeMpesaSTKPush(
         businessShortCode: "151030",
         transactionType: TransactionType.CustomerPayBillOnline,
         amount: amount,
         partyA: phone,
         partyB: "151030",
         callBackURL: "my call back",
         accountReference: "Sakahapa payment",
         phoneNumber: phone,
         baseUri: Uri(scheme: "https", host: "sandbox.safaricom.co.ke"),
         transactionDesc: "purchase",
         passKey:"####",
     );`

thats how it is

**Comment by Brightmuk** [comment]
Have you tested with my paybill?

**Comment by keronei** [comment]
Yes I did tested.

What puzzles is the fact that the response is from Mpesa, meaning there's a
small chance that it has to do with the paybill supporting online
transactions.

Maybe there's a need to test it in another platform with LMNO
implementation, just to be sure.

**Comment by Brightmuk** [comment]
That's strange because i had implemented the same earlier ,but using django-daraja which worked fine.

**Comment by Brightmuk** [comment]
Does the api differentiate production and sandbox mode?

**Comment by keronei** [comment]
Not really, you are the one to determine by supplying the base url, which
will specify whether it is sandbox.safaricom or live.safaricom...

You can go ahead and request to go live so that you can receive a passkey
which could better be usable with a production paybill, this could better
the chance, although it's not recommended.

Let me get back to you when I'll have better information pertaining to this
issue.

**Comment by Brightmuk** [comment]
I know i did turn a blind eye on it, but, I think it would be nice if you mentioned it on the readme . Personally thats what brought me the error

**Comment by keronei** [comment]
Noted.
I'll make the changes.
Good Luck.
